name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  generate-sources:
    name: Generate Go sources
    runs-on: ubuntu-22.04
    steps:
    - name: Check out plugin
      uses: actions/checkout@v5

    - name: Check out reference parser
      uses: actions/checkout@v5
      with:
        repository: yaml/yaml-reference-parser-clj
        ref: a867cac0568aeb453f9bfae0b2339da983019d07
        path: repos/yaml-reference-parser-clj

    - name: Generate Go sources
      run: make generate YAML_PARSER_DIR=repos/yaml-reference-parser-clj

    - name: Upload generated sources
      uses: actions/upload-artifact@v6
      with:
        name: generated-sources
        path: internal/glojure
        retention-days: 1

  test-linux:
    name: Test ${{ matrix.platform }}
    needs: generate-sources
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - platform: linux-x64
          runner: ubuntu-22.04
        - platform: linux-aarch64
          runner: ubuntu-22.04-arm
    steps:
    - name: Check out plugin
      uses: actions/checkout@v5

    - name: Check out reference parser
      uses: actions/checkout@v5
      with:
        repository: yaml/yaml-reference-parser-clj
        ref: a867cac0568aeb453f9bfae0b2339da983019d07
        path: repos/yaml-reference-parser-clj

    - name: Download generated sources
      uses: actions/download-artifact@v7
      with:
        name: generated-sources
        path: internal/glojure

    - name: Test plugin
      run: |
        make test \
          YAML_PARSER_DIR=repos/yaml-reference-parser-clj \
          USE_GENERATED_SOURCES=1

  test-macos:
    name: Test ${{ matrix.platform }}
    needs: generate-sources
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - platform: macos-x64
          runner: macos-15-intel
        - platform: macos-arm64
          runner: macos-15
    steps:
    - name: Check out plugin
      uses: actions/checkout@v5

    - name: Check out reference parser
      uses: actions/checkout@v5
      with:
        repository: yaml/yaml-reference-parser-clj
        ref: a867cac0568aeb453f9bfae0b2339da983019d07
        path: repos/yaml-reference-parser-clj

    - name: Download generated sources
      uses: actions/download-artifact@v7
      with:
        name: generated-sources
        path: internal/glojure

    - name: Test plugin
      run: |
        make test \
          YAML_PARSER_DIR=repos/yaml-reference-parser-clj \
          USE_GENERATED_SOURCES=1
