// Code generated by glojure codegen. DO NOT EDIT.

package json_DASH_comments

import (
	fmt "fmt"
	lang "github.com/glojurelang/glojure/pkg/lang"
	runtime "github.com/glojurelang/glojure/pkg/runtime"
	reflect "reflect"
	regexp4 "regexp"
	atomic "sync/atomic"
)

var aotDirectFn0 lang.FnFunc7
var aotDirectFn1 lang.FnFunc3
var aotDirectFn2 lang.FnFunc1
var aotDirectFn3 lang.FnFunc3
var aotDirectFn4 lang.FnFunc1
var aotDirectFn5 lang.FnFunc7
var aotDirectFn6 lang.FnFunc6
var aotDirectFn7 lang.FnFunc3
var aotDirectFn8 lang.FnFunc1
var aotDirectFn9 lang.FnFunc2
var aotDirectFn10 lang.FnFunc3
var aotDirectFn11 lang.FnFunc3
var aotDirectFn12 lang.FnFunc1
var aotDirectFn13 lang.FnFunc1
var aotDirectFn14 lang.FnFunc2
var aotDirectFn15 lang.FnFunc2
var aotDirectFn16 lang.FnFunc1
var aotDirectFn17 lang.FnFunc1
var aotDirectFn18 lang.FnFunc3
var aotDirectFn19 lang.FnFunc1

var aotKeywordMapShape0 = lang.NewKeywordMapShape("header-indent", "content-indent")

type aotKeywordMapStorage0 struct {
	lang.Map
	values [2]any
}

func aotKeywordMapNew0(v0 any, v1 any) *lang.Map {
	storage := &aotKeywordMapStorage0{}
	storage.values = [2]any{v0, v1}
	return lang.InitStaticKeywordMap(
		&storage.Map,
		aotKeywordMapShape0,
		storage.values[:],
	)
}

var aotKeywordSite0 lang.KeywordSite
var aotKeywordSite1 lang.KeywordSite
var aotKeywordMapShape1 = lang.NewKeywordMapShape("start", "end", "text")

type aotKeywordMapStorage1 struct {
	lang.Map
	values [3]any
}

func aotKeywordMapNew1(v0 any, v1 any, v2 any) *lang.Map {
	storage := &aotKeywordMapStorage1{}
	storage.values = [3]any{v0, v1, v2}
	return lang.InitStaticKeywordMap(
		&storage.Map,
		aotKeywordMapShape1,
		storage.values[:],
	)
}

var aotKeywordMapShape2 = lang.NewKeywordMapShape("options")

type aotKeywordMapStorage2 struct {
	lang.Map
	values [1]any
}

func aotKeywordMapNew2(v0 any) *lang.Map {
	storage := &aotKeywordMapStorage2{}
	storage.values = [1]any{v0}
	return lang.InitStaticKeywordMap(
		&storage.Map,
		aotKeywordMapShape2,
		storage.values[:],
	)
}

var aotKeywordMapShape3 = lang.NewKeywordMapShape("position")

type aotKeywordMapStorage3 struct {
	lang.Map
	values [1]any
}

func aotKeywordMapNew3(v0 any) *lang.Map {
	storage := &aotKeywordMapStorage3{}
	storage.values = [1]any{v0}
	return lang.InitStaticKeywordMap(
		&storage.Map,
		aotKeywordMapShape3,
		storage.values[:],
	)
}
func aotLinkFn1(vr *lang.Var) lang.FnFunc1 {
	if vr.IsBound() {
		return aotLinkBoundFn1(vr)
	}
	var linked atomic.Pointer[lang.FnFunc1]
	return func(p0 any) any {
		if fn := linked.Load(); fn != nil {
			return (*fn)(p0)
		}
		if !vr.IsBound() {
			return lang.Apply1(checkDerefVar(vr), p0)
		}
		fn := aotLinkBoundFn1(vr)
		linked.Store(&fn)
		return fn(p0)
	}
}

func aotLinkBoundFn1(vr *lang.Var) lang.FnFunc1 {
	fn := checkDerefVar(vr)
	if direct, ok := lang.DirectFn1(fn); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn1); ok {
		return fixed.Invoke1
	}
	return func(p0 any) any { return lang.Apply1(fn, p0) }
}

func aotLinkFn2(vr *lang.Var) lang.FnFunc2 {
	if vr.IsBound() {
		return aotLinkBoundFn2(vr)
	}
	var linked atomic.Pointer[lang.FnFunc2]
	return func(p0 any, p1 any) any {
		if fn := linked.Load(); fn != nil {
			return (*fn)(p0, p1)
		}
		if !vr.IsBound() {
			return lang.Apply2(checkDerefVar(vr), p0, p1)
		}
		fn := aotLinkBoundFn2(vr)
		linked.Store(&fn)
		return fn(p0, p1)
	}
}

func aotLinkBoundFn2(vr *lang.Var) lang.FnFunc2 {
	fn := checkDerefVar(vr)
	if direct, ok := lang.DirectFn2(fn); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn2); ok {
		return fixed.Invoke2
	}
	return func(p0 any, p1 any) any { return lang.Apply2(fn, p0, p1) }
}

func aotLinkFn3(vr *lang.Var) lang.FnFunc3 {
	if vr.IsBound() {
		return aotLinkBoundFn3(vr)
	}
	var linked atomic.Pointer[lang.FnFunc3]
	return func(p0 any, p1 any, p2 any) any {
		if fn := linked.Load(); fn != nil {
			return (*fn)(p0, p1, p2)
		}
		if !vr.IsBound() {
			return lang.Apply3(checkDerefVar(vr), p0, p1, p2)
		}
		fn := aotLinkBoundFn3(vr)
		linked.Store(&fn)
		return fn(p0, p1, p2)
	}
}

func aotLinkBoundFn3(vr *lang.Var) lang.FnFunc3 {
	fn := checkDerefVar(vr)
	if direct, ok := lang.DirectFn3(fn); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn3); ok {
		return fixed.Invoke3
	}
	return func(p0 any, p1 any, p2 any) any { return lang.Apply3(fn, p0, p1, p2) }
}

func init() {
	runtime.RegisterNSLoader("yamlstar_plugin/json_comments", LoadNS)
}

func checkDerefVar(v *lang.Var) any {
	if v.IsMacro() {
		panic(lang.NewIllegalArgumentError(fmt.Sprintf("can't take value of macro: %v", v)))
	}
	return v.Get()
}

func checkArity(args []any, expected int) {
	if len(args) != expected {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

func checkArityGTE(args []any, min int) {
	if len(args) < min {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

// LoadNS initializes the namespace "yamlstar-plugin.json-comments"
func LoadNS() {
	sym_advance_DASH_context := lang.NewSymbolUnchecked("advance-context")
	sym_after_DASH_comment_QMARK_ := lang.NewSymbolUnchecked("after-comment?")
	sym_blank_QMARK_ := lang.NewSymbolUnchecked("blank?")
	sym_block_DASH_comment_DASH_end := lang.NewSymbolUnchecked("block-comment-end")
	sym_block_DASH_header := lang.NewSymbolUnchecked("block-header")
	sym_block_DASH_header_DASH_before_QMARK_ := lang.NewSymbolUnchecked("block-header-before?")
	sym_block_DASH_header_DASH_pattern := lang.NewSymbolUnchecked("block-header-pattern")
	sym_block_DASH_header_DASH_prefix_DASH_pattern := lang.NewSymbolUnchecked("block-header-prefix-pattern")
	sym_block_DASH_scalar_DASH_ranges := lang.NewSymbolUnchecked("block-scalar-ranges")
	sym_character := lang.NewSymbolUnchecked("character")
	sym_characters := lang.NewSymbolUnchecked("characters")
	sym_clojure_DOT_core := lang.NewSymbolUnchecked("clojure.core")
	sym_clojure_DOT_string := lang.NewSymbolUnchecked("clojure.string")
	sym_comment := lang.NewSymbolUnchecked("comment")
	sym_comment_DASH_boundary_QMARK_ := lang.NewSymbolUnchecked("comment-boundary?")
	sym_conj := lang.NewSymbolUnchecked("conj")
	sym_contains_QMARK_ := lang.NewSymbolUnchecked("contains?")
	sym_context_DASH_after_DASH_character := lang.NewSymbolUnchecked("context-after-character")
	sym_document_DASH_marker_DASH_before_QMARK_ := lang.NewSymbolUnchecked("document-marker-before?")
	sym_end := lang.NewSymbolUnchecked("end")
	sym_ex_DASH_info := lang.NewSymbolUnchecked("ex-info")
	sym_indentation := lang.NewSymbolUnchecked("indentation")
	sym_index_DASH_of := lang.NewSymbolUnchecked("index-of")
	sym_input := lang.NewSymbolUnchecked("input")
	sym_join := lang.NewSymbolUnchecked("join")
	sym_json_DASH_colon_DASH_before_QMARK_ := lang.NewSymbolUnchecked("json-colon-before?")
	sym_json_DASH_token_DASH_before_QMARK_ := lang.NewSymbolUnchecked("json-token-before?")
	sym_json_DASH_token_DASH_pattern := lang.NewSymbolUnchecked("json-token-pattern")
	sym_length := lang.NewSymbolUnchecked("length")
	sym_line_DASH_comment_DASH_end := lang.NewSymbolUnchecked("line-comment-end")
	sym_line_DASH_records := lang.NewSymbolUnchecked("line-records")
	sym_line_DASH_start := lang.NewSymbolUnchecked("line-start")
	sym_mask_DASH_comment := lang.NewSymbolUnchecked("mask-comment")
	sym_options_DASH_edn := lang.NewSymbolUnchecked("options-edn")
	sym_parse := lang.NewSymbolUnchecked("parse")
	sym_parse_DASH_events := lang.NewSymbolUnchecked("parse-events")
	sym_parse_DASH_long := lang.NewSymbolUnchecked("parse-long")
	sym_parser := lang.NewSymbolUnchecked("parser")
	sym_position := lang.NewSymbolUnchecked("position")
	sym_prefix_DASH_eligible_QMARK_ := lang.NewSymbolUnchecked("prefix-eligible?")
	sym_quote_DASH_start_QMARK_ := lang.NewSymbolUnchecked("quote-start?")
	sym_quoted_DASH_end_QMARK_ := lang.NewSymbolUnchecked("quoted-end?")
	sym_re_DASH_find := lang.NewSymbolUnchecked("re-find")
	sym_re_DASH_matches := lang.NewSymbolUnchecked("re-matches")
	sym_read_DASH_string := lang.NewSymbolUnchecked("read-string")
	sym_replace := lang.NewSymbolUnchecked("replace")
	sym_replace_DASH_first := lang.NewSymbolUnchecked("replace-first")
	sym_sanitize_DASH_comments := lang.NewSymbolUnchecked("sanitize-comments")
	sym_second := lang.NewSymbolUnchecked("second")
	sym_seq_QMARK_ := lang.NewSymbolUnchecked("seq?")
	sym_slash_DASH_position := lang.NewSymbolUnchecked("slash-position")
	sym_start := lang.NewSymbolUnchecked("start")
	sym_str := lang.NewSymbolUnchecked("str")
	sym_structural_DASH_boundary_QMARK_ := lang.NewSymbolUnchecked("structural-boundary?")
	sym_subvec := lang.NewSymbolUnchecked("subvec")
	sym_text := lang.NewSymbolUnchecked("text")
	sym_text_DASH_between := lang.NewSymbolUnchecked("text-between")
	sym_to_DASH_array := lang.NewSymbolUnchecked("to-array")
	sym_trim := lang.NewSymbolUnchecked("trim")
	sym_value_DASH_start := lang.NewSymbolUnchecked("value-start")
	sym_vec := lang.NewSymbolUnchecked("vec")
	sym_whitespace_QMARK_ := lang.NewSymbolUnchecked("whitespace?")
	sym_yaml_DASH_parser_DOT_core := lang.NewSymbolUnchecked("yaml-parser.core")
	sym_yamlstar_DASH_plugin_DOT_json_DASH_comments := lang.NewSymbolUnchecked("yamlstar-plugin.json-comments")
	kw_arglists := lang.NewKeyword("arglists")
	kw_column := lang.NewKeyword("column")
	kw_content_DASH_indent := lang.NewKeyword("content-indent")
	kw_doc := lang.NewKeyword("doc")
	kw_double := lang.NewKeyword("double")
	kw_end := lang.NewKeyword("end")
	kw_end_DASH_column := lang.NewKeyword("end-column")
	kw_end_DASH_line := lang.NewKeyword("end-line")
	kw_file := lang.NewKeyword("file")
	kw_header_DASH_indent := lang.NewKeyword("header-indent")
	kw_line := lang.NewKeyword("line")
	kw_ns := lang.NewKeyword("ns")
	kw_private := lang.NewKeyword("private")
	kw_single := lang.NewKeyword("single")
	kw_start := lang.NewKeyword("start")
	kw_text := lang.NewKeyword("text")
	// var clojure.core/conj
	var_clojure_DOT_core_conj := lang.InternVarName(sym_clojure_DOT_core, sym_conj)
	// var clojure.core/contains?
	var_clojure_DOT_core_contains_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_contains_QMARK_)
	// var clojure.core/ex-info
	var_clojure_DOT_core_ex_DASH_info := lang.InternVarName(sym_clojure_DOT_core, sym_ex_DASH_info)
	// var clojure.core/parse-long
	var_clojure_DOT_core_parse_DASH_long := lang.InternVarName(sym_clojure_DOT_core, sym_parse_DASH_long)
	// var clojure.core/re-find
	var_clojure_DOT_core_re_DASH_find := lang.InternVarName(sym_clojure_DOT_core, sym_re_DASH_find)
	// var clojure.core/re-matches
	var_clojure_DOT_core_re_DASH_matches := lang.InternVarName(sym_clojure_DOT_core, sym_re_DASH_matches)
	// var clojure.core/read-string
	var_clojure_DOT_core_read_DASH_string := lang.InternVarName(sym_clojure_DOT_core, sym_read_DASH_string)
	// var clojure.core/second
	var_clojure_DOT_core_second := lang.InternVarName(sym_clojure_DOT_core, sym_second)
	// var clojure.core/seq?
	var_clojure_DOT_core_seq_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_seq_QMARK_)
	// var clojure.core/subvec
	var_clojure_DOT_core_subvec := lang.InternVarName(sym_clojure_DOT_core, sym_subvec)
	// var clojure.core/to-array
	var_clojure_DOT_core_to_DASH_array := lang.InternVarName(sym_clojure_DOT_core, sym_to_DASH_array)
	// var clojure.core/vec
	var_clojure_DOT_core_vec := lang.InternVarName(sym_clojure_DOT_core, sym_vec)
	// var clojure.string/blank?
	var_clojure_DOT_string_blank_QMARK_ := lang.InternVarName(sym_clojure_DOT_string, sym_blank_QMARK_)
	// var clojure.string/index-of
	var_clojure_DOT_string_index_DASH_of := lang.InternVarName(sym_clojure_DOT_string, sym_index_DASH_of)
	// var clojure.string/join
	var_clojure_DOT_string_join := lang.InternVarName(sym_clojure_DOT_string, sym_join)
	// var clojure.string/replace
	var_clojure_DOT_string_replace := lang.InternVarName(sym_clojure_DOT_string, sym_replace)
	// var clojure.string/replace-first
	var_clojure_DOT_string_replace_DASH_first := lang.InternVarName(sym_clojure_DOT_string, sym_replace_DASH_first)
	// var clojure.string/trim
	var_clojure_DOT_string_trim := lang.InternVarName(sym_clojure_DOT_string, sym_trim)
	// var yaml-parser.core/parse
	var_yaml_DASH_parser_DOT_core_parse := lang.InternVarName(sym_yaml_DASH_parser_DOT_core, sym_parse)
	// var yamlstar-plugin.json-comments/advance-context
	var_yamlstar_DASH_plugin_DOT_json_DASH_comments_advance_DASH_context := lang.InternVarName(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments, sym_advance_DASH_context)
	// var yamlstar-plugin.json-comments/block-comment-end
	var_yamlstar_DASH_plugin_DOT_json_DASH_comments_block_DASH_comment_DASH_end := lang.InternVarName(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments, sym_block_DASH_comment_DASH_end)
	// var yamlstar-plugin.json-comments/block-header
	var_yamlstar_DASH_plugin_DOT_json_DASH_comments_block_DASH_header := lang.InternVarName(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments, sym_block_DASH_header)
	// var yamlstar-plugin.json-comments/block-header-before?
	var_yamlstar_DASH_plugin_DOT_json_DASH_comments_block_DASH_header_DASH_before_QMARK_ := lang.InternVarName(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments, sym_block_DASH_header_DASH_before_QMARK_)
	// var yamlstar-plugin.json-comments/block-header-pattern
	var_yamlstar_DASH_plugin_DOT_json_DASH_comments_block_DASH_header_DASH_pattern := lang.InternVarName(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments, sym_block_DASH_header_DASH_pattern)
	// var yamlstar-plugin.json-comments/block-header-prefix-pattern
	var_yamlstar_DASH_plugin_DOT_json_DASH_comments_block_DASH_header_DASH_prefix_DASH_pattern := lang.InternVarName(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments, sym_block_DASH_header_DASH_prefix_DASH_pattern)
	// var yamlstar-plugin.json-comments/block-scalar-ranges
	var_yamlstar_DASH_plugin_DOT_json_DASH_comments_block_DASH_scalar_DASH_ranges := lang.InternVarName(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments, sym_block_DASH_scalar_DASH_ranges)
	// var yamlstar-plugin.json-comments/comment-boundary?
	var_yamlstar_DASH_plugin_DOT_json_DASH_comments_comment_DASH_boundary_QMARK_ := lang.InternVarName(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments, sym_comment_DASH_boundary_QMARK_)
	// var yamlstar-plugin.json-comments/context-after-character
	var_yamlstar_DASH_plugin_DOT_json_DASH_comments_context_DASH_after_DASH_character := lang.InternVarName(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments, sym_context_DASH_after_DASH_character)
	// var yamlstar-plugin.json-comments/document-marker-before?
	var_yamlstar_DASH_plugin_DOT_json_DASH_comments_document_DASH_marker_DASH_before_QMARK_ := lang.InternVarName(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments, sym_document_DASH_marker_DASH_before_QMARK_)
	// var yamlstar-plugin.json-comments/indentation
	var_yamlstar_DASH_plugin_DOT_json_DASH_comments_indentation := lang.InternVarName(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments, sym_indentation)
	// var yamlstar-plugin.json-comments/json-colon-before?
	var_yamlstar_DASH_plugin_DOT_json_DASH_comments_json_DASH_colon_DASH_before_QMARK_ := lang.InternVarName(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments, sym_json_DASH_colon_DASH_before_QMARK_)
	// var yamlstar-plugin.json-comments/json-token-before?
	var_yamlstar_DASH_plugin_DOT_json_DASH_comments_json_DASH_token_DASH_before_QMARK_ := lang.InternVarName(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments, sym_json_DASH_token_DASH_before_QMARK_)
	// var yamlstar-plugin.json-comments/json-token-pattern
	var_yamlstar_DASH_plugin_DOT_json_DASH_comments_json_DASH_token_DASH_pattern := lang.InternVarName(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments, sym_json_DASH_token_DASH_pattern)
	// var yamlstar-plugin.json-comments/line-comment-end
	var_yamlstar_DASH_plugin_DOT_json_DASH_comments_line_DASH_comment_DASH_end := lang.InternVarName(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments, sym_line_DASH_comment_DASH_end)
	// var yamlstar-plugin.json-comments/line-records
	var_yamlstar_DASH_plugin_DOT_json_DASH_comments_line_DASH_records := lang.InternVarName(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments, sym_line_DASH_records)
	// var yamlstar-plugin.json-comments/mask-comment
	var_yamlstar_DASH_plugin_DOT_json_DASH_comments_mask_DASH_comment := lang.InternVarName(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments, sym_mask_DASH_comment)
	// var yamlstar-plugin.json-comments/parse-events
	var_yamlstar_DASH_plugin_DOT_json_DASH_comments_parse_DASH_events := lang.InternVarName(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments, sym_parse_DASH_events)
	// var yamlstar-plugin.json-comments/quote-start?
	var_yamlstar_DASH_plugin_DOT_json_DASH_comments_quote_DASH_start_QMARK_ := lang.InternVarName(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments, sym_quote_DASH_start_QMARK_)
	// var yamlstar-plugin.json-comments/sanitize-comments
	var_yamlstar_DASH_plugin_DOT_json_DASH_comments_sanitize_DASH_comments := lang.InternVarName(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments, sym_sanitize_DASH_comments)
	// var yamlstar-plugin.json-comments/structural-boundary?
	var_yamlstar_DASH_plugin_DOT_json_DASH_comments_structural_DASH_boundary_QMARK_ := lang.InternVarName(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments, sym_structural_DASH_boundary_QMARK_)
	// var yamlstar-plugin.json-comments/text-between
	var_yamlstar_DASH_plugin_DOT_json_DASH_comments_text_DASH_between := lang.InternVarName(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments, sym_text_DASH_between)
	// var yamlstar-plugin.json-comments/whitespace?
	var_yamlstar_DASH_plugin_DOT_json_DASH_comments_whitespace_QMARK_ := lang.InternVarName(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments, sym_whitespace_QMARK_)
	aotExternalFn13 := aotLinkFn2(var_clojure_DOT_core_contains_QMARK_)
	aotExternalFn14 := aotLinkFn1(var_clojure_DOT_string_trim)
	aotExternalFn15 := aotLinkFn1(var_clojure_DOT_core_second)
	aotExternalFn16 := aotLinkFn3(var_clojure_DOT_string_replace_DASH_first)
	aotExternalFn17 := aotLinkFn3(var_clojure_DOT_string_replace)
	aotExternalFn18 := aotLinkFn1(var_clojure_DOT_string_blank_QMARK_)
	aotExternalFn19 := aotLinkFn1(var_clojure_DOT_core_read_DASH_string)
	aotExternalFn2 := aotLinkFn2(var_clojure_DOT_core_re_DASH_matches)
	aotExternalFn21 := aotLinkFn2(var_clojure_DOT_core_ex_DASH_info)
	aotExternalFn22 := aotLinkFn1(var_yaml_DASH_parser_DOT_core_parse)
	aotExternalFn23 := aotLinkFn2(var_clojure_DOT_string_index_DASH_of)
	aotExternalFn24 := aotLinkFn1(var_clojure_DOT_core_vec)
	aotExternalFn26 := aotLinkFn1(var_clojure_DOT_string_join)
	aotExternalFn27 := aotLinkFn3(var_clojure_DOT_core_conj)
	aotExternalFn28 := aotLinkFn3(var_clojure_DOT_core_subvec)
	aotExternalFn3 := aotLinkFn2(var_clojure_DOT_core_re_DASH_find)
	aotExternalFn5 := aotLinkFn1(var_clojure_DOT_core_parse_DASH_long)
	aotExternalFn7 := aotLinkFn1(var_clojure_DOT_core_seq_QMARK_)
	aotExternalFn9 := aotLinkFn1(var_clojure_DOT_core_to_DASH_array)
	// reference fmt to avoid unused import error
	_ = fmt.Printf
	// reference reflect to avoid unused import error
	_ = reflect.TypeOf
	ns := lang.FindOrCreateNamespace(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments)
	_ = ns
	{ // refer vars from clojure.core
		srcNS := lang.FindOrCreateNamespace(sym_clojure_DOT_core)
		ns.ReferAllSnapshot(srcNS, []string{
			"*loaded-libs*",
			"*loading-verbosely*",
			"*pending-paths*",
			"-protocols",
			">0?",
			">1?",
			"add-doc-and-meta",
			"array",
			"assert-args",
			"assert-valid-fdecl",
			"binding-conveyor-fn",
			"case-map",
			"check-cyclic-dependency",
			"check-valid-options",
			"data-reader-urls",
			"data-reader-var",
			"def-aset",
			"deref-as-map",
			"deref-future",
			"elide-top-frames",
			"emit-extend-protocol",
			"emit-extend-type",
			"emit-hinted-impl",
			"filter-key",
			"fits-table?",
			"global-hierarchy",
			"into1",
			"libspec?",
			"lift-ns",
			"load-all",
			"load-data-reader-file",
			"load-data-readers",
			"load-lib",
			"load-libs",
			"load-one",
			"max-mask-bits",
			"max-switch-table-size",
			"maybe-destructured",
			"maybe-min-hash",
			"merge-hash-collisions",
			"mk-bound-fn",
			"nary-inline",
			"normalize-slurp-opts",
			"parse-impls",
			"parsing-err",
			"pr-on",
			"prep-hashes",
			"prep-ints",
			"prependss",
			"preserving-reduced",
			"print-initialized",
			"print-map",
			"print-meta",
			"print-object",
			"print-prefix-map",
			"print-sequential",
			"print-tagged-object",
			"print-throwable",
			"protocol?",
			"reduce1",
			"root-directory",
			"root-resource",
			"serialized-require",
			"setup-reference",
			"shift-mask",
			"sigs",
			"spread",
			"strip-ns",
			"system-newline",
			"tapset",
			"throw-if",
		})
	}
	ns.AddAlias(sym_str, lang.FindOrCreateNamespace(sym_clojure_DOT_string))
	ns.AddAlias(sym_parser, lang.FindOrCreateNamespace(sym_yaml_DASH_parser_DOT_core))
	var closed0 any
	var closed1 any
	var closed2 any
	var closed3 any
	var closed4 any
	var closed5 any
	var closed6 any
	var closed7 any
	{
		closed0 = regexp4.MustCompile("[1-9]")
	}
	{
		closed1 = regexp4.MustCompile("[ \\t]*")
	}
	{
		closed2 = regexp4.MustCompile("^( *)")
	}
	{
		closed3 = regexp4.MustCompile("^(?:-|\\?)\\s+")
	}
	{
		closed4 = regexp4.MustCompile("^(?:-|\\?)\\s+")
	}
	{
		closed5 = regexp4.MustCompile("^(?:---|\\.\\.\\.)\\s+")
	}
	{
		closed6 = regexp4.MustCompile("^(?:---|\\.\\.\\.)\\s+")
	}
	{
		closed7 = regexp4.MustCompile("[^\\r\\n]")
	}
	// advance-context
	{
		tmp0 := sym_advance_DASH_context
		var tmp1 lang.FnFunc7
		tmp1 = lang.FnFunc7(func(p0, p1, p2, p3, p4, p5, p6 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			v4 := p2
			_ = v4
			v5 := p3
			_ = v5
			v6 := p4
			_ = v6
			v7 := p5
			_ = v7
			v8 := p6
			_ = v8
			var tmp9 any
			{ // let
				// let binding "position"
				var v10 any = v4
				_ = v10
				// let binding "line-start"
				var v11 any = v6
				_ = v11
				// let binding "value-start"
				var v12 any = v7
				_ = v12
				// let binding "prefix-eligible?"
				var v13 any = v8
				_ = v13
				for {
					var tmp14 any
					tmp15 := lang.Numbers.Gte(v10, v5)
					if lang.IsTruthy(tmp15) {
						tmp16 := lang.NewVector(v11, v12, v13)
						tmp14 = tmp16
					} else {
						var tmp17 any
						{ // let
							// let binding "vec__67"
							tmp18 := aotDirectFn6(v2, v3, v10, v11, v12, v13)
							var v19 any = tmp18
							_ = v19
							// let binding "line-start"
							tmp20 := runtime.RT.NthDefault(v19, lang.IntCast(int64(0)), nil)
							var v21 any = tmp20
							_ = v21
							// let binding "value-start"
							tmp22 := runtime.RT.NthDefault(v19, lang.IntCast(int64(1)), nil)
							var v23 any = tmp22
							_ = v23
							// let binding "prefix-eligible?"
							tmp24 := runtime.RT.NthDefault(v19, lang.IntCast(int64(2)), nil)
							var v25 any = tmp24
							_ = v25
							tmp27 := lang.Numbers.Inc(v10)
							var tmp26 any = tmp27
							var tmp28 any = v21
							var tmp29 any = v23
							var tmp30 any = v25
							v10 = tmp26
							v11 = tmp28
							v12 = tmp29
							v13 = tmp30
							continue
						} // end let
						tmp14 = tmp17
					}
					tmp9 = tmp14
					break
				}
			} // end let
			return tmp9
		})
		aotDirectFn0 = tmp1
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_advance_DASH_context = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_advance_DASH_context.SetMetaLazyMacro(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar_plugin/json_comments.glj", kw_line, int(194), kw_column, int(8), kw_end_DASH_line, int(194), kw_end_DASH_column, int(22), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_characters, sym_length, sym_start, sym_end, sym_line_DASH_start, sym_value_DASH_start, sym_prefix_DASH_eligible_QMARK_)), kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments))
		}, false)
	}
	// block-comment-end
	{
		tmp0 := sym_block_DASH_comment_DASH_end
		var tmp1 lang.FnFunc3
		tmp1 = lang.FnFunc3(func(p0, p1, p2 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			v4 := p2
			_ = v4
			var tmp5 any
			{ // let
				// let binding "position"
				var v6 any = v4
				_ = v6
				for {
					var tmp7 any
					tmp8 := lang.Numbers.Inc(v6)
					tmp9 := lang.Numbers.Gte(tmp8, v3)
					if lang.IsTruthy(tmp9) {
					} else {
						var tmp10 any
						var tmp11 any
						{ // let
							// let binding "and__0__auto__"
							tmp12 := runtime.RT.Nth(v2, lang.IntCast(v6))
							tmp13 := lang.Equals(lang.NewChar(42), tmp12)
							var v14 any = tmp13
							_ = v14
							var tmp15 any
							if lang.IsTruthy(v14) {
								tmp16 := lang.Numbers.Inc(v6)
								tmp17 := runtime.RT.Nth(v2, lang.IntCast(tmp16))
								tmp18 := lang.Equals(lang.NewChar(47), tmp17)
								tmp15 = tmp18
							} else {
								tmp15 = v14
							}
							tmp11 = tmp15
						} // end let
						if lang.IsTruthy(tmp11) {
							tmp12 := lang.Numbers.Add(v6, int64(2))
							tmp10 = tmp12
						} else {
							tmp14 := lang.Numbers.Inc(v6)
							var tmp13 any = tmp14
							v6 = tmp13
							continue
						}
						tmp7 = tmp10
					}
					tmp5 = tmp7
					break
				}
			} // end let
			return tmp5
		})
		aotDirectFn1 = tmp1
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_block_DASH_comment_DASH_end = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_block_DASH_comment_DASH_end.SetMetaLazyMacro(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar_plugin/json_comments.glj", kw_line, int(163), kw_column, int(8), kw_end_DASH_line, int(163), kw_end_DASH_column, int(24), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_characters, sym_length, sym_position)), kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments))
		}, false)
	}
	// block-header-pattern
	{
		tmp0 := sym_block_DASH_header_DASH_pattern
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_block_DASH_header_DASH_pattern = ns.InternWithValue(tmp0, regexp4.MustCompile("^( *)(?:(?:.*: )|(?:- )|(?:\\? ))?[|>]([1-9]?[+-]?|[+-]?[1-9]?)(?: *(?:#|//|/\\*).*)?$"), true)
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_block_DASH_header_DASH_pattern.SetMetaLazyMacro(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "yamlstar_plugin/json_comments.glj", kw_line, int(9), kw_column, int(6), kw_end_DASH_line, int(9), kw_end_DASH_column, int(35), kw_private, true, kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments))
		}, false)
	}
	// block-header-prefix-pattern
	{
		tmp0 := sym_block_DASH_header_DASH_prefix_DASH_pattern
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_block_DASH_header_DASH_prefix_DASH_pattern = ns.InternWithValue(tmp0, regexp4.MustCompile("^( *)(?:(?:.*: )|(?:- )|(?:\\? ))?[|>](?:[1-9]?[+-]?|[+-]?[1-9]?)$"), true)
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_block_DASH_header_DASH_prefix_DASH_pattern.SetMetaLazyMacro(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "yamlstar_plugin/json_comments.glj", kw_line, int(14), kw_column, int(6), kw_end_DASH_line, int(14), kw_end_DASH_column, int(42), kw_private, true, kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments))
		}, false)
	}
	// block-scalar-ranges
	{
		tmp0 := sym_block_DASH_scalar_DASH_ranges
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 any
			{ // let
				// let binding "records"
				tmp4 := aotDirectFn12(v2)
				var v5 any = tmp4
				_ = v5
				// let binding "block"
				var v6 any = nil
				_ = v6
				// let binding "ranges"
				tmp7 := lang.NewVector()
				var v8 any = tmp7
				_ = v8
				for {
					var tmp9 any
					{ // let
						// let binding "temp__0__auto__"
						tmp10 := lang.First(v5)
						var v11 any = tmp10
						_ = v11
						var tmp12 any
						if lang.IsTruthy(v11) {
							var tmp13 any
							{ // let
								// let binding "map__66"
								var v14 any = v11
								_ = v14
								// let binding "map__66"
								var tmp15 any
								tmp16 := aotExternalFn7(v14)
								if lang.IsTruthy(tmp16) {
									var tmp17 any
									tmp18 := lang.Next(v14)
									if lang.IsTruthy(tmp18) {
										tmp19 := aotExternalFn9(v14)
										tmp20 := lang.Apply1(lang.NewPersistentArrayMapAsIfByAssoc, tmp19)
										tmp17 = tmp20
									} else {
										var tmp21 any
										tmp22 := lang.IsSeqTruthy(v14)
										if tmp22 {
											tmp23 := lang.First(v14)
											tmp21 = tmp23
										} else {
											tmp24 := lang.Apply0(lang.NewMap)
											tmp21 = tmp24
										}
										tmp17 = tmp21
									}
									tmp15 = tmp17
								} else {
									tmp15 = v14
								}
								var v25 any = tmp15
								_ = v25
								// let binding "start"
								tmp26 := runtime.RT.Get(v25, kw_start)
								var v27 any = tmp26
								_ = v27
								// let binding "end"
								tmp28 := runtime.RT.Get(v25, kw_end)
								var v29 any = tmp28
								_ = v29
								// let binding "text"
								tmp30 := runtime.RT.Get(v25, kw_text)
								var v31 any = tmp30
								_ = v31
								var tmp32 any
								{ // let
									// let binding "indent"
									tmp33 := aotDirectFn8(v31)
									var v34 any = tmp33
									_ = v34
									// let binding "blank?"
									tmp35 := aotExternalFn2(closed1, v31)
									tmp36 := runtime.RT.BooleanCast(tmp35)
									var v37 any = tmp36
									_ = v37
									// let binding "content-indent"
									tmp38 := aotKeywordSite0.Get(kw_content_DASH_indent, v6, nil)
									var v39 any = tmp38
									_ = v39
									// let binding "content?"
									var tmp40 any
									{ // let
										// let binding "and__0__auto__"
										var v41 any = v6
										_ = v41
										var tmp42 any
										if lang.IsTruthy(v41) {
											var tmp43 any
											{ // let
												// let binding "or__0__auto__"
												var v44 any = v37
												_ = v44
												var tmp45 any
												if lang.IsTruthy(v44) {
													tmp45 = v44
												} else {
													var tmp46 any
													{ // let
														// let binding "or__0__auto__"
														var tmp47 any
														{ // let
															// let binding "and__0__auto__"
															var v48 any = v39
															_ = v48
															var tmp49 any
															if lang.IsTruthy(v48) {
																tmp50 := lang.Numbers.Gte(v34, v39)
																tmp49 = tmp50
															} else {
																tmp49 = v48
															}
															tmp47 = tmp49
														} // end let
														var v48 any = tmp47
														_ = v48
														var tmp49 any
														if lang.IsTruthy(v48) {
															tmp49 = v48
														} else {
															var tmp50 any
															{ // let
																// let binding "and__0__auto__"
																tmp51 := lang.Identical(v39, nil)
																var v52 any = tmp51
																_ = v52
																var tmp53 any
																if lang.IsTruthy(v52) {
																	tmp54 := aotKeywordSite1.Get(kw_header_DASH_indent, v6, nil)
																	tmp55 := lang.Numbers.Gt(v34, tmp54)
																	tmp53 = tmp55
																} else {
																	tmp53 = v52
																}
																tmp50 = tmp53
															} // end let
															tmp49 = tmp50
														}
														tmp46 = tmp49
													} // end let
													tmp45 = tmp46
												}
												tmp43 = tmp45
											} // end let
											tmp42 = tmp43
										} else {
											tmp42 = v41
										}
										tmp40 = tmp42
									} // end let
									var v41 any = tmp40
									_ = v41
									var tmp42 any
									if lang.IsTruthy(v41) {
										tmp44 := lang.Next(v5)
										var tmp43 any = tmp44
										var tmp46 any
										var tmp47 any
										{ // let
											// let binding "or__0__auto__"
											var v48 any = v37
											_ = v48
											var tmp49 any
											if lang.IsTruthy(v48) {
												tmp49 = v48
											} else {
												tmp49 = v39
											}
											tmp47 = tmp49
										} // end let
										if lang.IsTruthy(tmp47) {
											tmp46 = v6
										} else {
											var tmp48 any = v6
											tmp48 = lang.Assoc(tmp48, kw_content_DASH_indent, v34)
											tmp46 = tmp48
										}
										var tmp45 any = tmp46
										tmp50 := lang.NewVector(v27, v29)
										tmp51 := lang.ConjAny(v8, tmp50)
										var tmp49 any = tmp51
										v5 = tmp43
										v6 = tmp45
										v8 = tmp49
										continue
									} else {
										tmp53 := lang.Next(v5)
										var tmp52 any = tmp53
										tmp55 := aotDirectFn2(v31)
										var tmp54 any = tmp55
										var tmp56 any = v8
										v5 = tmp52
										v6 = tmp54
										v8 = tmp56
										continue
									}
									tmp32 = tmp42
								} // end let
								tmp13 = tmp32
							} // end let
							tmp12 = tmp13
						} else {
							tmp12 = v8
						}
						tmp9 = tmp12
					} // end let
					tmp3 = tmp9
					break
				}
			} // end let
			return tmp3
		})
		aotDirectFn4 = tmp1
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_block_DASH_scalar_DASH_ranges = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_block_DASH_scalar_DASH_ranges.SetMetaLazyMacro(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar_plugin/json_comments.glj", kw_line, int(63), kw_column, int(8), kw_end_DASH_line, int(63), kw_end_DASH_column, int(26), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_characters)), kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments))
		}, false)
	}
	// comment-boundary?
	{
		tmp0 := sym_comment_DASH_boundary_QMARK_
		var tmp1 lang.FnFunc7
		tmp1 = lang.FnFunc7(func(p0, p1, p2, p3, p4, p5, p6 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			v4 := p2
			_ = v4
			v5 := p3
			_ = v5
			v6 := p4
			_ = v6
			v7 := p5
			_ = v7
			v8 := p6
			_ = v8
			var tmp9 any
			{ // let
				// let binding "simple-boundary?"
				var tmp10 any
				{ // let
					// let binding "or__0__auto__"
					tmp11 := lang.Numbers.IsZero(v3)
					var v12 any = tmp11
					_ = v12
					var tmp13 any
					if lang.IsTruthy(v12) {
						tmp13 = v12
					} else {
						var tmp14 any
						{ // let
							// let binding "or__0__auto__"
							var v15 any = v4
							_ = v15
							var tmp16 any
							if lang.IsTruthy(v15) {
								tmp16 = v15
							} else {
								var tmp17 any
								{ // let
									// let binding "or__0__auto__"
									var v18 any = v5
									_ = v18
									var tmp19 any
									if lang.IsTruthy(v18) {
										tmp19 = v18
									} else {
										var tmp20 any
										{ // let
											// let binding "or__0__auto__"
											tmp21 := aotDirectFn9(v2, v3)
											var v22 any = tmp21
											_ = v22
											var tmp23 any
											if lang.IsTruthy(v22) {
												tmp23 = v22
											} else {
												var tmp24 any
												{ // let
													// let binding "previous"
													tmp25 := lang.Numbers.Dec(v3)
													tmp26 := runtime.RT.Nth(v2, lang.IntCast(tmp25))
													var v27 any = tmp26
													_ = v27
													var tmp28 any
													{ // let
														// let binding "or__0__auto__"
														tmp29 := aotDirectFn19(v27)
														var v30 any = tmp29
														_ = v30
														var tmp31 any
														if lang.IsTruthy(v30) {
															tmp31 = v30
														} else {
															tmp32 := aotDirectFn17(v27)
															tmp31 = tmp32
														}
														tmp28 = tmp31
													} // end let
													tmp24 = tmp28
												} // end let
												tmp23 = tmp24
											}
											tmp20 = tmp23
										} // end let
										tmp19 = tmp20
									}
									tmp17 = tmp19
								} // end let
								tmp16 = tmp17
							}
							tmp14 = tmp16
						} // end let
						tmp13 = tmp14
					}
					tmp10 = tmp13
				} // end let
				var v11 any = tmp10
				_ = v11
				var tmp12 any
				if lang.IsTruthy(v11) {
					tmp13 := lang.NewVector(true, v8)
					tmp12 = tmp13
				} else {
					var tmp14 any
					tmp15 := !lang.IsTruthy(v8)
					if tmp15 {
						tmp16 := lang.NewVector(false, false)
						tmp14 = tmp16
					} else {
						var tmp17 any
						{ // let
							// let binding "or__0__auto__"
							tmp18 := aotDirectFn10(v2, v7, v3)
							var v19 any = tmp18
							_ = v19
							var tmp20 any
							if lang.IsTruthy(v19) {
								tmp20 = v19
							} else {
								var tmp21 any
								{ // let
									// let binding "or__0__auto__"
									tmp22 := aotDirectFn7(v2, v7, v3)
									var v23 any = tmp22
									_ = v23
									var tmp24 any
									if lang.IsTruthy(v23) {
										tmp24 = v23
									} else {
										tmp25 := aotDirectFn3(v2, v6, v3)
										tmp24 = tmp25
									}
									tmp21 = tmp24
								} // end let
								tmp20 = tmp21
							}
							tmp17 = tmp20
						} // end let
						tmp18 := lang.NewVector(tmp17, false)
						tmp14 = tmp18
					}
					tmp12 = tmp14
				}
				tmp9 = tmp12
			} // end let
			return tmp9
		})
		aotDirectFn5 = tmp1
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_comment_DASH_boundary_QMARK_ = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_comment_DASH_boundary_QMARK_.SetMetaLazyMacro(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar_plugin/json_comments.glj", kw_line, int(124), kw_column, int(8), kw_end_DASH_line, int(124), kw_end_DASH_column, int(24), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_characters, sym_position, sym_quoted_DASH_end_QMARK_, sym_after_DASH_comment_QMARK_, sym_line_DASH_start, sym_value_DASH_start, sym_prefix_DASH_eligible_QMARK_)), kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments))
		}, false)
	}
	// context-after-character
	{
		tmp0 := sym_context_DASH_after_DASH_character
		var tmp1 lang.FnFunc6
		tmp1 = lang.FnFunc6(func(p0, p1, p2, p3, p4, p5 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			v4 := p2
			_ = v4
			v5 := p3
			_ = v5
			v6 := p4
			_ = v6
			v7 := p5
			_ = v7
			var tmp8 any
			{ // let
				// let binding "character"
				tmp9 := runtime.RT.Nth(v2, lang.IntCast(v4))
				var v10 any = tmp9
				_ = v10
				// let binding "next-character"
				var tmp11 any
				tmp12 := lang.Numbers.Inc(v4)
				tmp13 := lang.Numbers.Lt(tmp12, v3)
				if lang.IsTruthy(tmp13) {
					tmp14 := lang.Numbers.Inc(v4)
					tmp15 := runtime.RT.Nth(v2, lang.IntCast(tmp14))
					tmp11 = tmp15
				} else {
				}
				var v16 any = tmp11
				_ = v16
				// let binding "previous-character"
				var tmp17 any
				tmp18 := lang.Numbers.IsPos(v4)
				if lang.IsTruthy(tmp18) {
					tmp19 := lang.Numbers.Dec(v4)
					tmp20 := runtime.RT.Nth(v2, lang.IntCast(tmp19))
					tmp17 = tmp20
				} else {
				}
				var v21 any = tmp17
				_ = v21
				var tmp22 any
				tmp23 := lang.NewSet(lang.NewChar(10), lang.NewChar(13))
				tmp24 := lang.Apply1(tmp23, v10)
				if lang.IsTruthy(tmp24) {
					tmp25 := lang.Numbers.Inc(v4)
					tmp26 := lang.Numbers.Inc(v4)
					tmp27 := lang.NewVector(tmp25, tmp26, true)
					tmp22 = tmp27
				} else {
					var tmp28 any
					tmp29 := lang.NewSet(lang.NewChar(44), lang.NewChar(91), lang.NewChar(123))
					tmp30 := lang.Apply1(tmp29, v10)
					if lang.IsTruthy(tmp30) {
						tmp31 := lang.Numbers.Inc(v4)
						tmp32 := lang.NewVector(v5, tmp31, true)
						tmp28 = tmp32
					} else {
						var tmp33 any
						var tmp34 any
						{ // let
							// let binding "and__0__auto__"
							tmp35 := lang.Equals(v10, lang.NewChar(58))
							var v36 any = tmp35
							_ = v36
							var tmp37 any
							if lang.IsTruthy(v36) {
								var tmp38 any
								{ // let
									// let binding "or__0__auto__"
									var tmp39 any
									{ // let
										// let binding "and__0__auto__"
										var v40 any = v16
										_ = v40
										var tmp41 any
										if lang.IsTruthy(v40) {
											tmp42 := aotDirectFn19(v16)
											tmp41 = tmp42
										} else {
											tmp41 = v40
										}
										tmp39 = tmp41
									} // end let
									var v40 any = tmp39
									_ = v40
									var tmp41 any
									if lang.IsTruthy(v40) {
										tmp41 = v40
									} else {
										tmp42 := lang.NewSet(lang.NewChar(34), lang.NewChar(39), lang.NewChar(93), lang.NewChar(125))
										tmp43 := aotExternalFn13(tmp42, v21)
										tmp41 = tmp43
									}
									tmp38 = tmp41
								} // end let
								tmp37 = tmp38
							} else {
								tmp37 = v36
							}
							tmp34 = tmp37
						} // end let
						if lang.IsTruthy(tmp34) {
							tmp35 := lang.Numbers.Inc(v4)
							tmp36 := lang.NewVector(v5, tmp35, true)
							tmp33 = tmp36
						} else {
							tmp37 := lang.NewVector(v5, v6, v7)
							tmp33 = tmp37
						}
						tmp28 = tmp33
					}
					tmp22 = tmp28
				}
				tmp8 = tmp22
			} // end let
			return tmp8
		})
		aotDirectFn6 = tmp1
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_context_DASH_after_DASH_character = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_context_DASH_after_DASH_character.SetMetaLazyMacro(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar_plugin/json_comments.glj", kw_line, int(173), kw_column, int(8), kw_end_DASH_line, int(173), kw_end_DASH_column, int(30), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_characters, sym_length, sym_position, sym_line_DASH_start, sym_value_DASH_start, sym_prefix_DASH_eligible_QMARK_)), kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments))
		}, false)
	}
	// document-marker-before?
	{
		tmp0 := sym_document_DASH_marker_DASH_before_QMARK_
		var tmp1 lang.FnFunc3
		tmp1 = lang.FnFunc3(func(p0, p1, p2 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			v4 := p2
			_ = v4
			var tmp5 any
			{ // let
				// let binding "value"
				tmp6 := aotDirectFn18(v2, v3, v4)
				tmp7 := aotExternalFn14(tmp6)
				var v8 any = tmp7
				_ = v8
				tmp9 := lang.NewSet("...", "---")
				tmp10 := aotExternalFn13(tmp9, v8)
				tmp5 = tmp10
			} // end let
			return tmp5
		})
		aotDirectFn7 = tmp1
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_document_DASH_marker_DASH_before_QMARK_ = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_document_DASH_marker_DASH_before_QMARK_.SetMetaLazyMacro(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar_plugin/json_comments.glj", kw_line, int(105), kw_column, int(8), kw_end_DASH_line, int(105), kw_end_DASH_column, int(30), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_characters, sym_value_DASH_start, sym_slash_DASH_position)), kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments))
		}, false)
	}
	// indentation
	{
		tmp0 := sym_indentation
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 any
			{ // let
				// let binding "or__0__auto__"
				tmp4 := aotExternalFn3(closed2, v2)
				tmp5 := aotExternalFn15(tmp4)
				var v6 any = tmp5
				_ = v6
				var tmp7 any
				if lang.IsTruthy(v6) {
					tmp7 = v6
				} else {
					tmp7 = ""
				}
				tmp3 = tmp7
			} // end let
			tmp4 := lang.Count(tmp3)
			return tmp4
		})
		aotDirectFn8 = tmp1
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_indentation = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_indentation.SetMetaLazyMacro(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar_plugin/json_comments.glj", kw_line, int(49), kw_column, int(8), kw_end_DASH_line, int(49), kw_end_DASH_column, int(18), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_text)), kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments))
		}, false)
	}
	// json-colon-before?
	{
		tmp0 := sym_json_DASH_colon_DASH_before_QMARK_
		var tmp1 lang.FnFunc2
		tmp1 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			var tmp4 any
			{ // let
				// let binding "and__0__auto__"
				tmp5 := lang.Numbers.IsPos(v3)
				var v6 any = tmp5
				_ = v6
				var tmp7 any
				if lang.IsTruthy(v6) {
					var tmp8 any
					{ // let
						// let binding "and__0__auto__"
						tmp9 := lang.Numbers.Dec(v3)
						tmp10 := runtime.RT.Nth(v2, lang.IntCast(tmp9))
						tmp11 := lang.Equals(lang.NewChar(58), tmp10)
						var v12 any = tmp11
						_ = v12
						var tmp13 any
						if lang.IsTruthy(v12) {
							var tmp14 any
							{ // let
								// let binding "and__0__auto__"
								tmp15 := lang.Numbers.Gt(v3, int64(1))
								var v16 any = tmp15
								_ = v16
								var tmp17 any
								if lang.IsTruthy(v16) {
									tmp18 := lang.NewSet(lang.NewChar(34), lang.NewChar(39), lang.NewChar(93), lang.NewChar(125))
									tmp19 := lang.Numbers.Minus(v3, int64(2))
									tmp20 := runtime.RT.Nth(v2, lang.IntCast(tmp19))
									tmp21 := aotExternalFn13(tmp18, tmp20)
									tmp17 = tmp21
								} else {
									tmp17 = v16
								}
								tmp14 = tmp17
							} // end let
							tmp13 = tmp14
						} else {
							tmp13 = v12
						}
						tmp8 = tmp13
					} // end let
					tmp7 = tmp8
				} else {
					tmp7 = v6
				}
				tmp4 = tmp7
			} // end let
			return tmp4
		})
		aotDirectFn9 = tmp1
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_json_DASH_colon_DASH_before_QMARK_ = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_json_DASH_colon_DASH_before_QMARK_.SetMetaLazyMacro(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar_plugin/json_comments.glj", kw_line, int(116), kw_column, int(8), kw_end_DASH_line, int(116), kw_end_DASH_column, int(25), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_characters, sym_position)), kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments))
		}, false)
	}
	// json-token-pattern
	{
		tmp0 := sym_json_DASH_token_DASH_pattern
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_json_DASH_token_DASH_pattern = ns.InternWithValue(tmp0, regexp4.MustCompile("(?:null|true|false|-?(?:0|[1-9][0-9]*)(?:\\.[0-9]+)?(?:[eE][+-]?[0-9]+)?)"), true)
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_json_DASH_token_DASH_pattern.SetMetaLazyMacro(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "yamlstar_plugin/json_comments.glj", kw_line, int(6), kw_column, int(6), kw_end_DASH_line, int(6), kw_end_DASH_column, int(33), kw_private, true, kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments))
		}, false)
	}
	// line-comment-end
	{
		tmp0 := sym_line_DASH_comment_DASH_end
		var tmp1 lang.FnFunc3
		tmp1 = lang.FnFunc3(func(p0, p1, p2 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			v4 := p2
			_ = v4
			var tmp5 any
			{ // let
				// let binding "position"
				var v6 any = v4
				_ = v6
				for {
					var tmp7 any
					var tmp8 any
					{ // let
						// let binding "or__0__auto__"
						tmp9 := lang.Numbers.Gte(v6, v3)
						var v10 any = tmp9
						_ = v10
						var tmp11 any
						if lang.IsTruthy(v10) {
							tmp11 = v10
						} else {
							tmp12 := lang.NewSet(lang.NewChar(10), lang.NewChar(13))
							tmp13 := runtime.RT.Nth(v2, lang.IntCast(v6))
							tmp14 := lang.Apply1(tmp12, tmp13)
							tmp11 = tmp14
						}
						tmp8 = tmp11
					} // end let
					if lang.IsTruthy(tmp8) {
						tmp7 = v6
					} else {
						tmp10 := lang.Numbers.Inc(v6)
						var tmp9 any = tmp10
						v6 = tmp9
						continue
					}
					tmp5 = tmp7
					break
				}
			} // end let
			return tmp5
		})
		aotDirectFn11 = tmp1
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_line_DASH_comment_DASH_end = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_line_DASH_comment_DASH_end.SetMetaLazyMacro(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar_plugin/json_comments.glj", kw_line, int(155), kw_column, int(8), kw_end_DASH_line, int(155), kw_end_DASH_column, int(23), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_characters, sym_length, sym_position)), kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments))
		}, false)
	}
	// line-records
	{
		tmp0 := sym_line_DASH_records
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 any
			{ // let
				// let binding "length"
				tmp4 := lang.Count(v2)
				var v5 any = tmp4
				_ = v5
				var tmp6 any
				{ // let
					// let binding "start"
					var v7 any = int64(0)
					_ = v7
					// let binding "records"
					tmp8 := lang.NewVector()
					var v9 any = tmp8
					_ = v9
					for {
						var tmp10 any
						tmp11 := lang.Numbers.Gte(v7, v5)
						if lang.IsTruthy(tmp11) {
							tmp10 = v9
						} else {
							var tmp12 any
							{ // let
								// let binding "end"
								var tmp13 any
								{ // let
									// let binding "position"
									var v14 any = v7
									_ = v14
									for {
										var tmp15 any
										var tmp16 any
										{ // let
											// let binding "and__0__auto__"
											tmp17 := lang.Numbers.Lt(v14, v5)
											var v18 any = tmp17
											_ = v18
											var tmp19 any
											if lang.IsTruthy(v18) {
												tmp20 := lang.NewSet(lang.NewChar(10), lang.NewChar(13))
												tmp21 := runtime.RT.Nth(v2, lang.IntCast(v14))
												tmp22 := lang.Apply1(tmp20, tmp21)
												tmp23 := !lang.IsTruthy(tmp22)
												tmp19 = tmp23
											} else {
												tmp19 = v18
											}
											tmp16 = tmp19
										} // end let
										if lang.IsTruthy(tmp16) {
											tmp18 := lang.Numbers.Inc(v14)
											var tmp17 any = tmp18
											v14 = tmp17
											continue
										} else {
											tmp15 = v14
										}
										tmp13 = tmp15
										break
									}
								} // end let
								var v14 any = tmp13
								_ = v14
								// let binding "next-start"
								var tmp15 any
								tmp16 := lang.Numbers.Gte(v14, v5)
								if lang.IsTruthy(tmp16) {
									tmp15 = v14
								} else {
									var tmp17 any
									var tmp18 any
									{ // let
										// let binding "and__0__auto__"
										tmp19 := runtime.RT.Nth(v2, lang.IntCast(v14))
										tmp20 := lang.Equals(lang.NewChar(13), tmp19)
										var v21 any = tmp20
										_ = v21
										var tmp22 any
										if lang.IsTruthy(v21) {
											var tmp23 any
											{ // let
												// let binding "and__0__auto__"
												tmp24 := lang.Numbers.Inc(v14)
												tmp25 := lang.Numbers.Lt(tmp24, v5)
												var v26 any = tmp25
												_ = v26
												var tmp27 any
												if lang.IsTruthy(v26) {
													tmp28 := lang.Numbers.Inc(v14)
													tmp29 := runtime.RT.Nth(v2, lang.IntCast(tmp28))
													tmp30 := lang.Equals(lang.NewChar(10), tmp29)
													tmp27 = tmp30
												} else {
													tmp27 = v26
												}
												tmp23 = tmp27
											} // end let
											tmp22 = tmp23
										} else {
											tmp22 = v21
										}
										tmp18 = tmp22
									} // end let
									if lang.IsTruthy(tmp18) {
										tmp19 := lang.Numbers.Add(v14, int64(2))
										tmp17 = tmp19
									} else {
										tmp20 := lang.Numbers.Inc(v14)
										tmp17 = tmp20
									}
									tmp15 = tmp17
								}
								var v21 any = tmp15
								_ = v21
								var tmp22 any = v21
								tmp24 := aotDirectFn18(v2, v7, v14)
								tmp25 := aotKeywordMapNew1(v7, v21, tmp24)
								tmp26 := lang.ConjAny(v9, tmp25)
								var tmp23 any = tmp26
								v7 = tmp22
								v9 = tmp23
								continue
							} // end let
							tmp10 = tmp12
						}
						tmp6 = tmp10
						break
					}
				} // end let
				tmp3 = tmp6
			} // end let
			return tmp3
		})
		aotDirectFn12 = tmp1
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_line_DASH_records = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_line_DASH_records.SetMetaLazyMacro(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar_plugin/json_comments.glj", kw_line, int(23), kw_column, int(8), kw_end_DASH_line, int(23), kw_end_DASH_column, int(19), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_characters)), kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments))
		}, false)
	}
	// mask-comment
	{
		tmp0 := sym_mask_DASH_comment
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			tmp3 := aotExternalFn17(v2, closed7, " ")
			return tmp3
		})
		aotDirectFn13 = tmp1
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_mask_DASH_comment = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_mask_DASH_comment.SetMetaLazyMacro(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar_plugin/json_comments.glj", kw_line, int(151), kw_column, int(8), kw_end_DASH_line, int(151), kw_end_DASH_column, int(19), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_comment)), kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments))
		}, false)
	}
	// parse-events
	{
		tmp0 := sym_parse_DASH_events
		var tmp1 lang.FnFunc2
		tmp1 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			var tmp4 any
			{ // let
				// let binding "options"
				var tmp5 any
				tmp6 := aotExternalFn18(v3)
				if lang.IsTruthy(tmp6) {
					tmp7 := lang.NewMap()
					tmp5 = tmp7
				} else {
					tmp8 := aotExternalFn19(v3)
					tmp5 = tmp8
				}
				var v9 any = tmp5
				_ = v9
				var tmp10 any
				tmp11 := lang.IsMap(v9)
				if tmp11 {
				} else {
					tmp12 := aotKeywordMapNew2(v9)
					tmp13 := aotExternalFn21("Plugin options must be an EDN map", tmp12)
					panic(tmp13)
				}
				_ = tmp10
				tmp14 := aotDirectFn16(v2)
				tmp15 := aotExternalFn22(tmp14)
				tmp4 = tmp15
			} // end let
			return tmp4
		})
		aotDirectFn14 = tmp1
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_parse_DASH_events = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_parse_DASH_events.SetMetaLazyMacro(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar_plugin/json_comments.glj", kw_line, int(332), kw_column, int(7), kw_end_DASH_line, int(332), kw_end_DASH_column, int(18), kw_arglists, lang.NewList(lang.NewVector(sym_input, sym_options_DASH_edn)), kw_doc, "Parse input and return the event vector before transport encoding.", kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments))
		}, false)
	}
	// quote-start?
	{
		tmp0 := sym_quote_DASH_start_QMARK_
		var tmp1 lang.FnFunc2
		tmp1 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			var tmp4 any
			{ // let
				// let binding "or__0__auto__"
				tmp5 := lang.Numbers.IsZero(v3)
				var v6 any = tmp5
				_ = v6
				var tmp7 any
				if lang.IsTruthy(v6) {
					tmp7 = v6
				} else {
					var tmp8 any
					{ // let
						// let binding "previous"
						tmp9 := lang.Numbers.Dec(v3)
						tmp10 := runtime.RT.Nth(v2, lang.IntCast(tmp9))
						var v11 any = tmp10
						_ = v11
						var tmp12 any
						{ // let
							// let binding "or__0__auto__"
							tmp13 := aotDirectFn19(v11)
							var v14 any = tmp13
							_ = v14
							var tmp15 any
							if lang.IsTruthy(v14) {
								tmp15 = v14
							} else {
								tmp16 := lang.NewSet(lang.NewChar(44), lang.NewChar(58), lang.NewChar(91), lang.NewChar(123), lang.NewChar(63))
								tmp17 := aotExternalFn13(tmp16, v11)
								tmp15 = tmp17
							}
							tmp12 = tmp15
						} // end let
						tmp8 = tmp12
					} // end let
					tmp7 = tmp8
				}
				tmp4 = tmp7
			} // end let
			return tmp4
		})
		aotDirectFn15 = tmp1
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_quote_DASH_start_QMARK_ = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_quote_DASH_start_QMARK_.SetMetaLazyMacro(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar_plugin/json_comments.glj", kw_line, int(144), kw_column, int(8), kw_end_DASH_line, int(144), kw_end_DASH_column, int(19), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_characters, sym_position)), kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments))
		}, false)
	}
	// sanitize-comments
	{
		tmp0 := sym_sanitize_DASH_comments
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 any
			var tmp4 any
			{ // let
				// let binding "and__0__auto__"
				tmp5 := aotExternalFn23(v2, "//")
				tmp6 := lang.Identical(tmp5, nil)
				var v7 any = tmp6
				_ = v7
				var tmp8 any
				if lang.IsTruthy(v7) {
					tmp9 := aotExternalFn23(v2, "/*")
					tmp10 := lang.Identical(tmp9, nil)
					tmp8 = tmp10
				} else {
					tmp8 = v7
				}
				tmp4 = tmp8
			} // end let
			if lang.IsTruthy(tmp4) {
				tmp3 = v2
			} else {
				var tmp5 any
				{ // let
					// let binding "characters"
					tmp6 := aotExternalFn24(v2)
					var v7 any = tmp6
					_ = v7
					// let binding "ranges"
					tmp8 := aotDirectFn4(v7)
					var v9 any = tmp8
					_ = v9
					// let binding "length"
					tmp10 := lang.Count(v7)
					var v11 any = tmp10
					_ = v11
					var tmp12 any
					{ // let
						// let binding "position"
						var v13 any = int64(0)
						_ = v13
						// let binding "ranges"
						var v14 any = v9
						_ = v14
						// let binding "output"
						tmp15 := lang.NewVector()
						var v16 any = tmp15
						_ = v16
						// let binding "copy-start"
						var v17 any = int64(0)
						_ = v17
						// let binding "quote"
						var v18 any = nil
						_ = v18
						// let binding "escaped?"
						var v19 any = false
						_ = v19
						// let binding "quoted-end?"
						var v20 any = false
						_ = v20
						// let binding "after-comment?"
						var v21 any = false
						_ = v21
						// let binding "line-start"
						var v22 any = int64(0)
						_ = v22
						// let binding "value-start"
						var v23 any = int64(0)
						_ = v23
						// let binding "prefix-eligible?"
						var v24 any = true
						_ = v24
						for {
							var tmp25 any
							tmp26 := lang.Numbers.Gte(v13, v11)
							if lang.IsTruthy(tmp26) {
								var tmp27 any
								tmp28 := lang.IsEmpty(v16)
								if tmp28 {
									tmp27 = v2
								} else {
									tmp29 := aotDirectFn18(v7, v17, v11)
									tmp30 := lang.ConjAny(v16, tmp29)
									tmp31 := aotExternalFn26(tmp30)
									tmp27 = tmp31
								}
								tmp25 = tmp27
							} else {
								var tmp32 any
								{ // let
									// let binding "temp__0__auto__"
									tmp33 := lang.First(v14)
									var v34 any = tmp33
									_ = v34
									var tmp35 any
									if lang.IsTruthy(v34) {
										var tmp36 any
										{ // let
											// let binding "vec__70"
											var v37 any = v34
											_ = v37
											// let binding "start"
											tmp38 := runtime.RT.NthDefault(v37, lang.IntCast(int64(0)), nil)
											var v39 any = tmp38
											_ = v39
											// let binding "end"
											tmp40 := runtime.RT.NthDefault(v37, lang.IntCast(int64(1)), nil)
											var v41 any = tmp40
											_ = v41
											var tmp42 any
											tmp43 := lang.Equals(v13, v39)
											if tmp43 {
												var tmp44 any
												{ // let
													// let binding "vec__73"
													tmp45 := aotDirectFn0(v7, v11, v13, v41, v22, v23, v24)
													var v46 any = tmp45
													_ = v46
													// let binding "line-start"
													tmp47 := runtime.RT.NthDefault(v46, lang.IntCast(int64(0)), nil)
													var v48 any = tmp47
													_ = v48
													// let binding "value-start"
													tmp49 := runtime.RT.NthDefault(v46, lang.IntCast(int64(1)), nil)
													var v50 any = tmp49
													_ = v50
													// let binding "prefix-eligible?"
													tmp51 := runtime.RT.NthDefault(v46, lang.IntCast(int64(2)), nil)
													var v52 any = tmp51
													_ = v52
													var tmp53 any = v41
													tmp55 := lang.Next(v14)
													var tmp54 any = tmp55
													var tmp56 any = v16
													var tmp57 any = v17
													var tmp58 any = nil
													var tmp59 any = false
													var tmp60 any = false
													var tmp61 any = false
													var tmp62 any = v48
													var tmp63 any = v50
													var tmp64 any = v52
													v13 = tmp53
													v14 = tmp54
													v16 = tmp56
													v17 = tmp57
													v18 = tmp58
													v19 = tmp59
													v20 = tmp60
													v21 = tmp61
													v22 = tmp62
													v23 = tmp63
													v24 = tmp64
													continue
												} // end let
												tmp42 = tmp44
											} else {
												var tmp45 any
												tmp46 := lang.Numbers.Gt(v13, v39)
												if lang.IsTruthy(tmp46) {
													var tmp47 any = v13
													tmp49 := lang.Next(v14)
													var tmp48 any = tmp49
													var tmp50 any = v16
													var tmp51 any = v17
													var tmp52 any = v18
													var tmp53 any = v19
													var tmp54 any = v20
													var tmp55 any = v21
													var tmp56 any = v22
													var tmp57 any = v23
													var tmp58 any = v24
													v13 = tmp47
													v14 = tmp48
													v16 = tmp50
													v17 = tmp51
													v18 = tmp52
													v19 = tmp53
													v20 = tmp54
													v21 = tmp55
													v22 = tmp56
													v23 = tmp57
													v24 = tmp58
													continue
												} else {
													var tmp59 any
													{ // let
														// let binding "character"
														tmp60 := runtime.RT.Nth(v7, lang.IntCast(v13))
														var v61 any = tmp60
														_ = v61
														// let binding "next-character"
														var tmp62 any
														tmp63 := lang.Numbers.Inc(v13)
														tmp64 := lang.Numbers.Lt(tmp63, v11)
														if lang.IsTruthy(tmp64) {
															tmp65 := lang.Numbers.Inc(v13)
															tmp66 := runtime.RT.Nth(v7, lang.IntCast(tmp65))
															tmp62 = tmp66
														} else {
														}
														var v67 any = tmp62
														_ = v67
														// let binding "vec__76"
														var tmp68 any
														var tmp69 any
														{ // let
															// let binding "and__0__auto__"
															tmp70 := lang.Equals(v61, lang.NewChar(47))
															var v71 any = tmp70
															_ = v71
															var tmp72 any
															if lang.IsTruthy(v71) {
																tmp73 := lang.NewSet(lang.NewChar(42), lang.NewChar(47))
																tmp74 := lang.Apply1(tmp73, v67)
																tmp72 = tmp74
															} else {
																tmp72 = v71
															}
															tmp69 = tmp72
														} // end let
														if lang.IsTruthy(tmp69) {
															tmp70 := aotDirectFn5(v7, v13, v20, v21, v22, v23, v24)
															tmp68 = tmp70
														} else {
															tmp71 := lang.NewVector(false, v24)
															tmp68 = tmp71
														}
														var v72 any = tmp68
														_ = v72
														// let binding "boundary?"
														tmp73 := runtime.RT.NthDefault(v72, lang.IntCast(int64(0)), nil)
														var v74 any = tmp73
														_ = v74
														// let binding "checked-prefix?"
														tmp75 := runtime.RT.NthDefault(v72, lang.IntCast(int64(1)), nil)
														var v76 any = tmp75
														_ = v76
														var tmp77 any
														if lang.IsTruthy(v18) {
															var tmp78 any
															{ // let
																// let binding "step"
																var tmp79 any
																var tmp80 any
																{ // let
																	// let binding "and__0__auto__"
																	tmp81 := lang.Equals(v18, kw_single)
																	var v82 any = tmp81
																	_ = v82
																	var tmp83 any
																	if lang.IsTruthy(v82) {
																		var tmp84 any
																		{ // let
																			// let binding "and__0__auto__"
																			tmp85 := lang.Equals(v61, lang.NewChar(39))
																			var v86 any = tmp85
																			_ = v86
																			var tmp87 any
																			if lang.IsTruthy(v86) {
																				tmp88 := lang.Equals(v67, lang.NewChar(39))
																				tmp87 = tmp88
																			} else {
																				tmp87 = v86
																			}
																			tmp84 = tmp87
																		} // end let
																		tmp83 = tmp84
																	} else {
																		tmp83 = v82
																	}
																	tmp80 = tmp83
																} // end let
																if lang.IsTruthy(tmp80) {
																	tmp79 = int64(2)
																} else {
																	tmp79 = int64(1)
																}
																var v81 any = tmp79
																_ = v81
																// let binding "single-end?"
																var tmp82 any
																{ // let
																	// let binding "and__0__auto__"
																	tmp83 := lang.Equals(v81, int64(1))
																	var v84 any = tmp83
																	_ = v84
																	var tmp85 any
																	if lang.IsTruthy(v84) {
																		var tmp86 any
																		{ // let
																			// let binding "and__0__auto__"
																			tmp87 := lang.Equals(v18, kw_single)
																			var v88 any = tmp87
																			_ = v88
																			var tmp89 any
																			if lang.IsTruthy(v88) {
																				tmp90 := lang.Equals(v61, lang.NewChar(39))
																				tmp89 = tmp90
																			} else {
																				tmp89 = v88
																			}
																			tmp86 = tmp89
																		} // end let
																		tmp85 = tmp86
																	} else {
																		tmp85 = v84
																	}
																	tmp82 = tmp85
																} // end let
																var v83 any = tmp82
																_ = v83
																// let binding "double-end?"
																var tmp84 any
																{ // let
																	// let binding "and__0__auto__"
																	tmp85 := lang.Equals(v18, kw_double)
																	var v86 any = tmp85
																	_ = v86
																	var tmp87 any
																	if lang.IsTruthy(v86) {
																		var tmp88 any
																		{ // let
																			// let binding "and__0__auto__"
																			tmp89 := lang.Equals(v61, lang.NewChar(34))
																			var v90 any = tmp89
																			_ = v90
																			var tmp91 any
																			if lang.IsTruthy(v90) {
																				tmp92 := !lang.IsTruthy(v19)
																				tmp91 = tmp92
																			} else {
																				tmp91 = v90
																			}
																			tmp88 = tmp91
																		} // end let
																		tmp87 = tmp88
																	} else {
																		tmp87 = v86
																	}
																	tmp84 = tmp87
																} // end let
																var v85 any = tmp84
																_ = v85
																// let binding "end"
																tmp86 := lang.Numbers.Add(v13, v81)
																var v87 any = tmp86
																_ = v87
																// let binding "vec__79"
																tmp88 := aotDirectFn0(v7, v11, v13, v87, v22, v23, v76)
																var v89 any = tmp88
																_ = v89
																// let binding "line-start"
																tmp90 := runtime.RT.NthDefault(v89, lang.IntCast(int64(0)), nil)
																var v91 any = tmp90
																_ = v91
																// let binding "value-start"
																tmp92 := runtime.RT.NthDefault(v89, lang.IntCast(int64(1)), nil)
																var v93 any = tmp92
																_ = v93
																// let binding "prefix-eligible?"
																tmp94 := runtime.RT.NthDefault(v89, lang.IntCast(int64(2)), nil)
																var v95 any = tmp94
																_ = v95
																var tmp96 any = v87
																var tmp97 any = v14
																var tmp98 any = v16
																var tmp99 any = v17
																var tmp101 any
																var tmp102 any
																{ // let
																	// let binding "or__0__auto__"
																	var v103 any = v83
																	_ = v103
																	var tmp104 any
																	if lang.IsTruthy(v103) {
																		tmp104 = v103
																	} else {
																		tmp104 = v85
																	}
																	tmp102 = tmp104
																} // end let
																if lang.IsTruthy(tmp102) {
																} else {
																	tmp101 = v18
																}
																var tmp100 any = tmp101
																var tmp104 any
																{ // let
																	// let binding "and__0__auto__"
																	tmp105 := lang.Equals(v18, kw_double)
																	var v106 any = tmp105
																	_ = v106
																	var tmp107 any
																	if lang.IsTruthy(v106) {
																		var tmp108 any
																		{ // let
																			// let binding "and__0__auto__"
																			tmp109 := lang.Equals(v61, lang.NewChar(92))
																			var v110 any = tmp109
																			_ = v110
																			var tmp111 any
																			if lang.IsTruthy(v110) {
																				tmp112 := !lang.IsTruthy(v19)
																				tmp111 = tmp112
																			} else {
																				tmp111 = v110
																			}
																			tmp108 = tmp111
																		} // end let
																		tmp107 = tmp108
																	} else {
																		tmp107 = v106
																	}
																	tmp104 = tmp107
																} // end let
																var tmp103 any = tmp104
																var tmp106 any
																{ // let
																	// let binding "or__0__auto__"
																	var v107 any = v83
																	_ = v107
																	var tmp108 any
																	if lang.IsTruthy(v107) {
																		tmp108 = v107
																	} else {
																		tmp108 = v85
																	}
																	tmp106 = tmp108
																} // end let
																var tmp105 any = tmp106
																var tmp107 any = false
																var tmp108 any = v91
																var tmp109 any = v93
																var tmp110 any = v95
																v13 = tmp96
																v14 = tmp97
																v16 = tmp98
																v17 = tmp99
																v18 = tmp100
																v19 = tmp103
																v20 = tmp105
																v21 = tmp107
																v22 = tmp108
																v23 = tmp109
																v24 = tmp110
																continue
															} // end let
															tmp77 = tmp78
														} else {
															var tmp79 any
															var tmp80 any
															{ // let
																// let binding "and__0__auto__"
																tmp81 := lang.NewSet(lang.NewChar(34), lang.NewChar(39))
																tmp82 := lang.Apply1(tmp81, v61)
																var v83 any = tmp82
																_ = v83
																var tmp84 any
																if lang.IsTruthy(v83) {
																	tmp85 := aotDirectFn15(v7, v13)
																	tmp84 = tmp85
																} else {
																	tmp84 = v83
																}
																tmp80 = tmp84
															} // end let
															if lang.IsTruthy(tmp80) {
																var tmp81 any
																{ // let
																	// let binding "vec__82"
																	tmp82 := aotDirectFn6(v7, v11, v13, v22, v23, v76)
																	var v83 any = tmp82
																	_ = v83
																	// let binding "line-start"
																	tmp84 := runtime.RT.NthDefault(v83, lang.IntCast(int64(0)), nil)
																	var v85 any = tmp84
																	_ = v85
																	// let binding "value-start"
																	tmp86 := runtime.RT.NthDefault(v83, lang.IntCast(int64(1)), nil)
																	var v87 any = tmp86
																	_ = v87
																	// let binding "prefix-eligible?"
																	tmp88 := runtime.RT.NthDefault(v83, lang.IntCast(int64(2)), nil)
																	var v89 any = tmp88
																	_ = v89
																	tmp91 := lang.Numbers.Inc(v13)
																	var tmp90 any = tmp91
																	var tmp92 any = v14
																	var tmp93 any = v16
																	var tmp94 any = v17
																	var tmp96 any
																	tmp97 := lang.Equals(v61, lang.NewChar(39))
																	if tmp97 {
																		tmp96 = kw_single
																	} else {
																		tmp96 = kw_double
																	}
																	var tmp95 any = tmp96
																	var tmp98 any = false
																	var tmp99 any = false
																	var tmp100 any = false
																	var tmp101 any = v85
																	var tmp102 any = v87
																	var tmp103 any = v89
																	v13 = tmp90
																	v14 = tmp92
																	v16 = tmp93
																	v17 = tmp94
																	v18 = tmp95
																	v19 = tmp98
																	v20 = tmp99
																	v21 = tmp100
																	v22 = tmp101
																	v23 = tmp102
																	v24 = tmp103
																	continue
																} // end let
																tmp79 = tmp81
															} else {
																var tmp82 any
																if lang.IsTruthy(v74) {
																	var tmp83 any
																	{ // let
																		// let binding "end"
																		var tmp84 any
																		tmp85 := lang.Equals(v67, lang.NewChar(47))
																		if tmp85 {
																			tmp86 := lang.Numbers.Add(v13, int64(2))
																			tmp87 := aotDirectFn11(v7, v11, tmp86)
																			tmp84 = tmp87
																		} else {
																			var tmp88 any
																			{ // let
																				// let binding "or__0__auto__"
																				tmp89 := lang.Numbers.Add(v13, int64(2))
																				tmp90 := aotDirectFn1(v7, v11, tmp89)
																				var v91 any = tmp90
																				_ = v91
																				var tmp92 any
																				if lang.IsTruthy(v91) {
																					tmp92 = v91
																				} else {
																					tmp93 := aotKeywordMapNew3(v13)
																					tmp94 := aotExternalFn21("Unterminated block comment", tmp93)
																					panic(tmp94)
																				}
																				tmp88 = tmp92
																			} // end let
																			tmp84 = tmp88
																		}
																		var v89 any = tmp84
																		_ = v89
																		// let binding "vec__85"
																		tmp90 := aotDirectFn0(v7, v11, v13, v89, v22, v23, v76)
																		var v91 any = tmp90
																		_ = v91
																		// let binding "line-start"
																		tmp92 := runtime.RT.NthDefault(v91, lang.IntCast(int64(0)), nil)
																		var v93 any = tmp92
																		_ = v93
																		// let binding "value-start"
																		tmp94 := runtime.RT.NthDefault(v91, lang.IntCast(int64(1)), nil)
																		var v95 any = tmp94
																		_ = v95
																		// let binding "prefix-eligible?"
																		tmp96 := runtime.RT.NthDefault(v91, lang.IntCast(int64(2)), nil)
																		var v97 any = tmp96
																		_ = v97
																		var tmp98 any = v89
																		var tmp99 any = v14
																		tmp101 := aotDirectFn18(v7, v17, v13)
																		tmp102 := aotDirectFn18(v7, v13, v89)
																		tmp103 := aotDirectFn13(tmp102)
																		tmp104 := aotExternalFn27(v16, tmp101, tmp103)
																		var tmp100 any = tmp104
																		var tmp105 any = v89
																		var tmp106 any = nil
																		var tmp107 any = false
																		var tmp108 any = false
																		var tmp109 any = true
																		var tmp110 any = v93
																		var tmp111 any = v95
																		var tmp112 any = v97
																		v13 = tmp98
																		v14 = tmp99
																		v16 = tmp100
																		v17 = tmp105
																		v18 = tmp106
																		v19 = tmp107
																		v20 = tmp108
																		v21 = tmp109
																		v22 = tmp110
																		v23 = tmp111
																		v24 = tmp112
																		continue
																	} // end let
																	tmp82 = tmp83
																} else {
																	var tmp84 any
																	{ // let
																		// let binding "vec__88"
																		tmp85 := aotDirectFn6(v7, v11, v13, v22, v23, v76)
																		var v86 any = tmp85
																		_ = v86
																		// let binding "line-start"
																		tmp87 := runtime.RT.NthDefault(v86, lang.IntCast(int64(0)), nil)
																		var v88 any = tmp87
																		_ = v88
																		// let binding "value-start"
																		tmp89 := runtime.RT.NthDefault(v86, lang.IntCast(int64(1)), nil)
																		var v90 any = tmp89
																		_ = v90
																		// let binding "prefix-eligible?"
																		tmp91 := runtime.RT.NthDefault(v86, lang.IntCast(int64(2)), nil)
																		var v92 any = tmp91
																		_ = v92
																		tmp94 := lang.Numbers.Inc(v13)
																		var tmp93 any = tmp94
																		var tmp95 any = v14
																		var tmp96 any = v16
																		var tmp97 any = v17
																		var tmp98 any = nil
																		var tmp99 any = false
																		var tmp100 any = false
																		var tmp101 any = false
																		var tmp102 any = v88
																		var tmp103 any = v90
																		var tmp104 any = v92
																		v13 = tmp93
																		v14 = tmp95
																		v16 = tmp96
																		v17 = tmp97
																		v18 = tmp98
																		v19 = tmp99
																		v20 = tmp100
																		v21 = tmp101
																		v22 = tmp102
																		v23 = tmp103
																		v24 = tmp104
																		continue
																	} // end let
																	tmp82 = tmp84
																}
																tmp79 = tmp82
															}
															tmp77 = tmp79
														}
														tmp59 = tmp77
													} // end let
													tmp45 = tmp59
												}
												tmp42 = tmp45
											}
											tmp36 = tmp42
										} // end let
										tmp35 = tmp36
									} else {
										var tmp37 any = v13
										tmp39 := lang.NewVector(v11, v11)
										tmp40 := lang.NewVector(tmp39)
										var tmp38 any = tmp40
										var tmp41 any = v16
										var tmp42 any = v17
										var tmp43 any = v18
										var tmp44 any = v19
										var tmp45 any = v20
										var tmp46 any = v21
										var tmp47 any = v22
										var tmp48 any = v23
										var tmp49 any = v24
										v13 = tmp37
										v14 = tmp38
										v16 = tmp41
										v17 = tmp42
										v18 = tmp43
										v19 = tmp44
										v20 = tmp45
										v21 = tmp46
										v22 = tmp47
										v23 = tmp48
										v24 = tmp49
										continue
									}
									tmp32 = tmp35
								} // end let
								tmp25 = tmp32
							}
							tmp12 = tmp25
							break
						}
					} // end let
					tmp5 = tmp12
				} // end let
				tmp3 = tmp5
			}
			return tmp3
		})
		aotDirectFn16 = tmp1
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_sanitize_DASH_comments = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_sanitize_DASH_comments.SetMetaLazyMacro(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar_plugin/json_comments.glj", kw_line, int(209), kw_column, int(7), kw_end_DASH_line, int(209), kw_end_DASH_column, int(23), kw_arglists, lang.NewList(lang.NewVector(sym_input)), kw_doc, "Replace JSON-style comments with spaces while preserving offsets.", kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments))
		}, false)
	}
	// structural-boundary?
	{
		tmp0 := sym_structural_DASH_boundary_QMARK_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			tmp3 := lang.NewSet(lang.NewChar(44), lang.NewChar(91), lang.NewChar(123), lang.NewChar(93), lang.NewChar(125))
			tmp4 := aotExternalFn13(tmp3, v2)
			return tmp4
		})
		aotDirectFn17 = tmp1
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_structural_DASH_boundary_QMARK_ = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_structural_DASH_boundary_QMARK_.SetMetaLazyMacro(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar_plugin/json_comments.glj", kw_line, int(89), kw_column, int(8), kw_end_DASH_line, int(89), kw_end_DASH_column, int(27), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_character)), kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments))
		}, false)
	}
	// text-between
	{
		tmp0 := sym_text_DASH_between
		var tmp1 lang.FnFunc3
		tmp1 = lang.FnFunc3(func(p0, p1, p2 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			v4 := p2
			_ = v4
			tmp5 := aotExternalFn28(v2, v3, v4)
			tmp6 := aotExternalFn26(tmp5)
			return tmp6
		})
		aotDirectFn18 = tmp1
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_text_DASH_between = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_text_DASH_between.SetMetaLazyMacro(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar_plugin/json_comments.glj", kw_line, int(19), kw_column, int(8), kw_end_DASH_line, int(19), kw_end_DASH_column, int(19), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_characters, sym_start, sym_end)), kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments))
		}, false)
	}
	// whitespace?
	{
		tmp0 := sym_whitespace_QMARK_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			tmp3 := lang.NewSet(lang.NewChar(32), lang.NewChar(9), lang.NewChar(10), lang.NewChar(13))
			tmp4 := aotExternalFn13(tmp3, v2)
			return tmp4
		})
		aotDirectFn19 = tmp1
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_whitespace_QMARK_ = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_whitespace_QMARK_.SetMetaLazyMacro(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar_plugin/json_comments.glj", kw_line, int(85), kw_column, int(8), kw_end_DASH_line, int(85), kw_end_DASH_column, int(18), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_character)), kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments))
		}, false)
	}
	// block-header
	{
		tmp0 := sym_block_DASH_header
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 any
			{ // let
				// let binding "temp__0__auto__"
				tmp4 := checkDerefVar(var_yamlstar_DASH_plugin_DOT_json_DASH_comments_block_DASH_header_DASH_pattern)
				tmp5 := aotExternalFn2(tmp4, v2)
				var v6 any = tmp5
				_ = v6
				var tmp7 any
				if lang.IsTruthy(v6) {
					var tmp8 any
					{ // let
						// let binding "match"
						var v9 any = v6
						_ = v9
						var tmp10 any
						{ // let
							// let binding "modifier"
							tmp11 := runtime.RT.Nth(v9, lang.IntCast(int64(2)))
							var v12 any = tmp11
							_ = v12
							// let binding "digit"
							tmp13 := aotExternalFn3(closed0, v12)
							var v14 any = tmp13
							_ = v14
							tmp15 := runtime.RT.Nth(v9, lang.IntCast(int64(1)))
							tmp16 := lang.Count(tmp15)
							var tmp17 any
							if lang.IsTruthy(v14) {
								tmp18 := runtime.RT.Nth(v9, lang.IntCast(int64(1)))
								tmp19 := lang.Count(tmp18)
								tmp20 := aotExternalFn5(v14)
								tmp21 := lang.Numbers.Add(tmp19, tmp20)
								tmp17 = tmp21
							} else {
							}
							tmp22 := aotKeywordMapNew0(tmp16, tmp17)
							tmp10 = tmp22
						} // end let
						tmp8 = tmp10
					} // end let
					tmp7 = tmp8
				} else {
				}
				tmp3 = tmp7
			} // end let
			return tmp3
		})
		aotDirectFn2 = tmp1
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_block_DASH_header = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_block_DASH_header.SetMetaLazyMacro(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar_plugin/json_comments.glj", kw_line, int(53), kw_column, int(8), kw_end_DASH_line, int(53), kw_end_DASH_column, int(19), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_text)), kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments))
		}, false)
	}
	// block-header-before?
	{
		tmp0 := sym_block_DASH_header_DASH_before_QMARK_
		var tmp1 lang.FnFunc3
		tmp1 = lang.FnFunc3(func(p0, p1, p2 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			v4 := p2
			_ = v4
			var tmp5 any
			{ // let
				// let binding "prefix"
				tmp6 := aotDirectFn18(v2, v3, v4)
				var v7 any = tmp6
				_ = v7
				tmp8 := checkDerefVar(var_yamlstar_DASH_plugin_DOT_json_DASH_comments_block_DASH_header_DASH_prefix_DASH_pattern)
				tmp9 := aotExternalFn2(tmp8, v7)
				tmp10 := runtime.RT.BooleanCast(tmp9)
				tmp5 = tmp10
			} // end let
			return tmp5
		})
		aotDirectFn3 = tmp1
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_block_DASH_header_DASH_before_QMARK_ = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_block_DASH_header_DASH_before_QMARK_.SetMetaLazyMacro(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar_plugin/json_comments.glj", kw_line, int(111), kw_column, int(8), kw_end_DASH_line, int(111), kw_end_DASH_column, int(27), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_characters, sym_line_DASH_start, sym_slash_DASH_position)), kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments))
		}, false)
	}
	// json-token-before?
	{
		tmp0 := sym_json_DASH_token_DASH_before_QMARK_
		var tmp1 lang.FnFunc3
		tmp1 = lang.FnFunc3(func(p0, p1, p2 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			v4 := p2
			_ = v4
			var tmp5 any
			{ // let
				// let binding "value"
				tmp6 := aotDirectFn18(v2, v3, v4)
				tmp7 := aotExternalFn14(tmp6)
				var v8 any = tmp7
				_ = v8
				// let binding "value"
				var tmp9 any
				tmp10 := aotExternalFn3(closed3, v8)
				if lang.IsTruthy(tmp10) {
					tmp11 := aotExternalFn16(v8, closed4, "")
					tmp9 = tmp11
				} else {
					tmp9 = v8
				}
				var v12 any = tmp9
				_ = v12
				// let binding "value"
				var tmp13 any
				tmp14 := aotExternalFn3(closed5, v12)
				if lang.IsTruthy(tmp14) {
					tmp15 := aotExternalFn16(v12, closed6, "")
					tmp13 = tmp15
				} else {
					tmp13 = v12
				}
				var v16 any = tmp13
				_ = v16
				tmp17 := checkDerefVar(var_yamlstar_DASH_plugin_DOT_json_DASH_comments_json_DASH_token_DASH_pattern)
				tmp18 := aotExternalFn2(tmp17, v16)
				tmp19 := runtime.RT.BooleanCast(tmp18)
				tmp5 = tmp19
			} // end let
			return tmp5
		})
		aotDirectFn10 = tmp1
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_json_DASH_token_DASH_before_QMARK_ = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DASH_plugin_DOT_json_DASH_comments_json_DASH_token_DASH_before_QMARK_.SetMetaLazyMacro(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar_plugin/json_comments.glj", kw_line, int(93), kw_column, int(8), kw_end_DASH_line, int(93), kw_end_DASH_column, int(25), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_characters, sym_value_DASH_start, sym_slash_DASH_position)), kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DASH_plugin_DOT_json_DASH_comments))
		}, false)
	}
}
